### ISSUE TITLE
Håndtere historiske identer

### ISSUE THREAD

**Issue by fraadsbrandth** [navikt/omsorgspenger-sak#10]
- Om person med identitetsnummer X ikke har noen sak, men hadde tidligere identitetsnummer Y med saksnummer Z skal det å hente saksnummer med identitetsnummer X henter saksnummer enten via rapid eller API også returnere saksnummer Z.

- https://navikt.github.io/pdl/#_bruk_av_identer_fra_pdl

- Sjekke først i databasen om vi har mappingen "lokalt". om ikke slå opp mot PDL

- Om vi finner saksnummer på tidligere ident bør det legges til en mapping mellom X og Z slik at vi slipper å gjøre samme PDL-oppslag hver gang dette forekommer.

**Comment by fraadsbrandth** [comment]
Det er mulig det er like enkelt å legge til integrasjon mot PDL direkte fra denne appen kun for å hente historiske identer. @albrektsson .

Da trenger vi i tilfelle ikke ta inn den kompleksiteten med å hente historiske i k9-personopplysninger - kun hente gjeldende AktørId slik som vi har snakket om.

**Comment by albrektsson** [comment]
@fraadsbrandth
