### ISSUE TITLE
Løse behov `HentIdentitetsnummerFraOmsorgspengerSaksnummer`

### ISSUE THREAD

**Issue by fraadsbrandth** [navikt/omsorgspenger-sak#18]
- Slå opp siste identitetsnummer vi har for alle saksnummer i databasen (feile om vi ikke finner, bør ikke skje)
- Hente siste identitetsnummer fra PDL for hvert enkelt identitetsnummer vi har i DB
- Legge de siste identitetsnummerne fra PDL i løsningen 

- Må avklares fra PDL-Doc/Høre på #mfn;
  - Om en person dør, vil identitetsnummeret da være `historisk` eller vil det alltid være det siste kjente identitestsnummer uavhengig av status på personen?

Behov:
```json
{
      "saksnummer": ["123","456"]
}
```

Løsning:
```json
{
      "identitetsnummer": {
                 "123": "111111111",
                 "456": "222222"
      }
}
```

**Comment by albrektsson** [comment]
Löses i rammemeldinger med hjälp av gjeldendeIdentitetsnummer som kommer från k9-personopplysninger.
